theme: jekyll-theme-minimal
title: "Project Dat4k : Are we in a time loop"
description: Trying to create a website 
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Example
    url: example
