

remote_theme: pages-themes/cayman@v0.2.0

plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: "Project Dat4k : Are we in a time loop"
description: Trying to create a website
show_downloads: True

header:
  image: /time_loop.jpg

styles:
  - "/_sass/styles.scss" # Point directly to the Sass file in _sass folder


navigation:
  - title : Home
    url : \
  - title : Project Dat4k
    url: /test/